objects/Private_Object__c.object
<CustomObject>
    <label>Private Object</label>
    <nameField>
        <label>Private Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Private Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Private Objects</relationshipLabel>
        <relationshipName>Private_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/PositivePermission_tests.cls
@isTest
private class PositivePermission_tests {
  @TestSetup
  static void testSetup(){
    Account a = TestFactory.getAccount('View For You!', true);
    Private_Object__c po = new Private_Object__c(account__c = a.id, notes__c = 'foo');
    insert po;
  }
  @isTest static void PermissionSetTest_Positive() {
    User u = TestFactory.generateUser('Custom user');
    System.runAs(u){
      Private_Object__c[] pos;
      Test.startTest();
      pos = [SELECT Id, Account__c, notes__c FROM Private_Object__c];
      Test.stopTest();
      system.assert(pos.size() == 1, 'a user with the permission set see any records');
    }
  }
}